[tool.poetry]
name = "sum"
version = "0.1.0"
description = ""
authors = ["Urban Kravjanský <u.kravjansky@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pylint = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
